<main>
    <div class="container">

        <div class="row" id="painel">

            <div class="col-8">

                <div class="row d-flex align-items-center item-carrinho">
                    <!-- Imagem -->
                    <div class="col-3">
                        <img class="img-fluid" src="https://source.unsplash.com/286x180?hamburguer">
                    </div>

                    <!-- Detalhes -->
                    <div class="col-4">
                        <h6>Nome do Hamburguer</h6>
                        <p>Lorem Ipsum is simply</p>
                    </div>

                    <!-- Quantidade de itens -->
                    <div class="col-3">
                        <button class="btn-car"><i class="fas fa-minus-square"></i></button>
                        <span class="quantidade-itens">1</span>
                        <button class="btn-car"><i class="fas fa-plus-square"></i></button>
                    </div>

                    <!-- Valor -->
                    <div class="col-2">
                        <span class="valor-item">R$ 00,00</span>
                    </div>

                </div>

            </div>
            <div class="col-4"></div>
        </div>
</main>