<body>
    <div class="card">
        <div class="card-header">Cadastrar-se</div>
        <div class="card-body">
            <form action="/cadastrar" method="post">
                <div class="form-group">
                    <label for="nome">Nome</label>
                    <input name="nome" type="text" class="form-control" id="nome" placeholder="Insira seu nome">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input name="email" type="email" class="form-control" id="email" placeholder="Insira seu email">
                </div>
                <div class="form-group">
                    <label for="senha">Senha</label>
                    <input name="senha" type="password" class="form-control" id="senha" placeholder="Insira sua senha">
                </div>
                
                <button type="submit" class="btn btn-primary">Cadastrar-se</button>
            </form>
            <div class="text-center">
                <a href="/">Já tenho uma conta</a>
            </div>
        </div>
    </div>