<form action="/registraHamburguer" method="post">
    <div class="form-group">
        <label for="nomeHamburguer">Nome do hamburguer</label>
        <input name='nome' id="nomeHamburguer" class="form-control" name="nome" type="text">
    </div>

    <div class="form-group">
        <label for="descricaoHamburguer">Descricao</label>
        <textarea name='descricao' id="descricaoHamburguer" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label for="descricaoHamburguer">Valor</label>
        <input name='valor' id="valorHamburguer" class="form-control" placeholder="R$ 00,00"></input>
    </div>

    <?php foreach ($this->view->ingredientes as $chave => $valor) { ?>

        <div class="form-check form-check-inline">
            <input name="ingredientes[]" class="form-check-input" type="checkbox" value="<?= $valor['id'] ?>">
            <label class="form-check-label"><?= $valor['nome'] ?></label>
        </div>

    <?php } ?>
    <button class="btn btn-block btn-primary mt-3">Registrar</button>
</form>

<div class="mt-4">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col-1">Id</th>
                <th scope="col-3">Nome</th>
                <th scope="col-4">Descrição</th>
                <th scope="col-4">Ingredientes</th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($this->view->hamburguers as $chave => $valor) { ?>
                <tr>
                    <th><?= $valor['id'] ?></th>
                    <td><?= $valor['nome'] ?></td>
                    <td><?= $valor['descricao'] ?></td>
                    <td><?= $valor['ingredientes'] ?></td>
                </tr>
            <?php } ?>
        </tbody>


    </table>

</div>

<script>
    const inputValor = document.querySelector('#valorHamburguer');
    inputValor.addEventListener('input', formatarValor);

    function formatarValor() {
        let valor = inputValor.value.replace(/\D/g, '');
        valor = (valor / 100).toFixed(2).replace('.', ',').replace(/(\d)(?=(\d{3})+,)/g, '$1.');

        inputValor.value = `R$ ${valor}`;
    }
</script>