<script>
    $(document).ready(function() {
        $('.add-car').click(function(event) {

            event.preventDefault();

            let id = $(this).attr('id')
            $.ajax({
                url: '/adicionar-carrinho',
                method: 'POST',
                data: {
                    id_hamburguer: id
                },
                success: function(response) {
                    $('#conteudo-modal').html('Adicionado ao carrinho!')
                    $('#myModal').modal('show');
                }
            });
        })
    })
</script>

<main>

    <div class="row justify-content-center">
        <?php foreach ($this->view->itens as $hamburguer => $dados) { ?>
            <div class="col-sm-6 col-md-4 card-deck mb-md-5">
                <div class="card" style="width: 18rem;">
                    <a href="/item?id=<?= $dados['id'] ?>"><img class="card-img-top" src="https://source.unsplash.com/286x180?hamburguer" alt="Card image cap"></a>
                    <div class="card-body">
                        <h5 class="card-title"><?= $dados['nome'] ?></h5>
                        <?php
                        $max_descricao = 100;
                        if (strlen($dados['descricao']) > $max_descricao) {
                            $descricao_resumida = substr($dados['descricao'], 0, $max_descricao) . '...';
                        } else {
                            $descricao_resumida = $dados['descricao'];
                        }
                        ?>
                        <p class="card-text mb-a"><?= $descricao_resumida ?></p>

                        <ul>
                            <?php
                            $ingredientes = explode(',', $dados['ingredientes']);
                            $primeiros_ingredientes = array_slice($ingredientes, 0, 4);
                            foreach ($primeiros_ingredientes as $ingrediente => $nome) {
                            ?>
                                <li><?= $nome ?></li>
                            <?php } ?>
                            <?php if (count($ingredientes) > 4) { ?>
                                <li>...</li>
                            <?php } ?>
                        </ul>
                    </div>

                    <div class="px-3 pb-3" style="margin-top: -15px">
                        <a href="/adicionar-carrinho" id="<?= $dados['id'] ?>" class="btn btn-primary btn-block add-car">Adicionar ao carrinho</a>
                    </div>

                </div>
            </div>
        <?php } ?>

    </div>
    </div>

    <div class="modal" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Hamburguer Adicionado</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="conteudo-modal"></p>
                </div>
                <div class="modal-footer">
                    <a href="/carrinho" class="btn btn-primary">Ir para o carrinho</a>
                    <button type="button" class="btn btn-success" data-dismiss="modal">Okay</button>
                </div>
            </div>
        </div>
    </div>

</main>