<div class="container">

    <?php if(empty($this->view->meusPedidos)) { ?>
        
        <div class="alert alert-info text-center" role="alert">
            <h4 class="alert-heading">Nenhum pedido ativo</h4>
            <p>Não encontramos nenhum pedido ativo. Assim que você finalizar sua compra, ela aparecerá aqui.</p>
        </div>

    <?php } else { ?>

    <?php foreach ($this->view->meusPedidos as $pedido => $dados_pedido) { ?>
        <div class="card card-color mb-3">
            <div class="card-header d-flex cabecalho-pedidos">
                <div>Número do pedido: #<?= $dados_pedido['id_pedido'] ?></div>
                <div class="mx-auto">Status: <?= $dados_pedido['status'] ?></div>
                <div class="mr-0">Valor total: R$ <?= $dados_pedido['valor'] ?></div>
            </div>
            <ul class="list-group list-group-flush">

                <?php foreach (json_decode($this->view->meusPedidos[$pedido]['hamburguers_pedido']) as $hamburguers => $dados_hamburguers) { ?>
                    <li class="list-group-item">
                        <div class="row d-flex align-items-center">
                            <div class="col-md-3">
                                <img src="https://source.unsplash.com/286x180?hamburguer" class="img-fluid" style="width: 200; height: 100px;" alt="Hambúrguer 1">
                            </div>
                            <div class="col-md-6">
                                <h5 class="card-title"><?= $dados_hamburguers->nome ?></h5>
                            </div>
                            <div class="col-md-3">
                                <span class="quantidade-item-pedido">Quantidade: <?= $dados_hamburguers->quantidade ?></span>
                            </div>
                        </div>
                    </li>
                <?php } ?>


            </ul>
        </div>
    <?php }} ?>

</div>

<?php
// echo '<pre>';
// print_r($this->view->meusPedidos);
// echo '</pre>';
?>