<div class="container">

    <?php foreach ($this->view->meusPedidos as $chave => $valor) { ?>
        <div class="card card-color">
            <div class="card-header d-flex cabecalho-pedidos">
                <div>Número do pedido: #<?= $valor['id_pedido'] ?></div>
                <div class="mx-auto">Status: <?= $valor['status'] ?></div>
                <div class="mr-0">Valor total: R$ <?= $valor['valor'] ?></div>
            </div>
            <ul class="list-group list-group-flush">

                <?php foreach (json_decode($this->view->meusPedidos[0]['hamburguers_pedido']) as $chave => $valor) { ?>
                    <li class="list-group-item">
                        <div class="row d-flex align-items-center">
                            <div class="col-md-3">
                                <img src="https://source.unsplash.com/286x180?hamburguer" class="img-fluid" style="width: 200; height: 100px;" alt="Hambúrguer 1">
                            </div>
                            <div class="col-md-6">
                                <h5 class="card-title"><?=$valor->nome?></h5>
                            </div>
                            <div class="col-md-3">
                                <span class="quantidade-item-pedido">Quantidade: <?=$valor->quantidade?></span>
                            </div>
                        </div>
                    </li>
                <?php } ?>


            </ul>
        </div>
    <?php } ?>

</div>

<?php
// echo '<pre>';
// print_r($this->view->meusPedidos);
// echo '</pre>';
?>