<div class="mb-3">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Pedido</th>
                <th scope="col">Usuario</th>
                <th scope="col">Hamburguers</th>
                <th scope="col">Valor</th>
                <th scope="col">Status</th>
                <th>Opções</th>

            </tr>
        </thead>

        <tbody>
            <?php include ('dadosPedidos.phtml') ?>
        </tbody>

    </table>
</div>

<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>