<?php

    if (empty($_GET)) {
        if($_SESSION['tipo'] == '2') {
            require_once 'ingredientes.phtml';
        } else if($_SESSION['tipo'] == '1') {
            require_once 'meusPedidos.phtml';
        }
    }

    // <!-- Hamburguers -->
    if (isset($_GET['hamburguers'])) {
        verificadorDePermissao();
        require_once 'hamburguers.phtml';
    }

    if (isset($_GET['pedidos'])) {
        verificadorDePermissao();
        require_once 'pedidos.phtml';
    }

    if (isset($_GET['meus_pedidos'])) {
        verificadorDePermissao();
        require_once 'meusPedidos.phtml';
    }

    
    function verificadorDePermissao() {
        if($_SESSION['tipo'] == '1') {
            header('LOCATION: /user');
        }
    }
?>