<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/647559b62c.js" crossorigin="anonymous"></script>

    <!-- Import do jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Imports do Bootstrap com jQuery e Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="estilo.css">

    <title>Hamburgueria</title>

    <script>
        function remover(id) {
            location.href = '/remover-ingrediente?id=' + id
        }

        function editar(id) {
            let ingrediente = $(`#ingrediente_${id}`);

            let template = `
            <form action="/editar-ingrediente?id=${id}" method="post" class="row">
                <input name="valor" class="col-8 form-control ml-2" type="text">
                <button class="col-3 btn btn-primary" type="submit">Atualizar</button>
            </form>
            `;

            ingrediente.html(template);
        }
    </script>

</head>

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-5">
        <div class="container">
            <a href="/home" class="navbar-brand">Hamburgueria</a>

            <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="menu">
                <ul class="navbar-nav" style="margin-left: auto;">

                    <!-- Carrinho -->
                    <li class="navbar-item icons mx-2">
                        <a href="/carrinho" class="nav-link">
                            <i class="fa-solid fa-cart-shopping"></i>
                        </a>
                    </li>

                    <!-- Página do usuário -->
                    <li class="navbar-item icons mx-2">
                        <a href="/user" class="nav-link">
                            <i class="fa-solid fa-user"></i>
                        </a>
                    </li>

                    <!-- Sair -->
                    <li class="navbar-item icons mx-2">
                        <a href="/sair" class="nav-link">
                            <i class="fa-solid fa-right-from-bracket"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container">

            <div class="row" id="painel">

                <div class="col-4">
                    <!-- Ingredientes -->
                    <div class="row">
                        <a href="/user">Ingredientes</a>
                    </div>
                    <!-- Hamburguers -->
                    <div class="row">
                        <a href="/user?hamburguers">Hamburguers</a>
                    </div>

                    <!-- Pedidos Adm -->
                    <div class="row">
                        <a style="border-bottom: 1px solid #C0C0C0;" href="/user?pedidos">Pedidos</a>
                    </div>

                </div>

                <div class="col-8">
                    <div id="conteudo">

                        <?= $this->content() ?>

                    </div>
                </div>
            </div>
    </main>
    </div>

</body>

</html>